"""Add ondelete CASCADE to RefreshToken

Revision ID: 3c8a5681a6b1
Revises: d3a8ba8bdde7
Create Date: 2026-01-15 04:22:40.676869

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3c8a5681a6b1"
down_revision: Union[str, None] = "d3a8ba8bdde7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("refreshtoken_user_id_fkey"), "refreshtoken", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "refreshtoken", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("refreshtoken_user_id_fkey", "refreshtoken", type_="foreignkey")
    op.create_foreign_key(
        op.f("refreshtoken_user_id_fkey"), "refreshtoken", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
