"""change recipe description field to instructions field

Revision ID: 4a9dc4a567a3
Revises: f7cd03f94e4a
Create Date: 2025-02-04 01:42:32.743041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a9dc4a567a3'
down_revision: Union[str, None] = 'f7cd03f94e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('recipe', sa.Column('instrutions', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('recipe', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('recipe', 'instrutions')
    op.drop_column('recipe', 'instructions')
    # ### end Alembic commands ###
