"""add calories field to ingredient

Revision ID: 5fbb87540f32
Revises: 92f0d59bbaab
Create Date: 2025-07-24 00:30:01.677563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5fbb87540f32'
down_revision: Union[str, None] = '92f0d59bbaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('calories', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'calories')
    # ### end Alembic commands ###
