"""added created_at field to GameSession

Revision ID: 6d6808607378
Revises: 81bdaea227a7
Create Date: 2026-02-11 01:42:13.001573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6d6808607378"
down_revision: Union[str, None] = "81bdaea227a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamesession",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.execute("UPDATE gamesession SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column("gamesession", "created_at", nullable=False)
    op.alter_column(
        "role",
        "scopes",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "role",
        "scopes",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_column("gamesession", "created_at")
    # ### end Alembic commands ###
