"""added created_at field to Recipe model

Revision ID: 81778f400be6
Revises: a1d4c07df17e
Create Date: 2026-02-26 15:28:28.818676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81778f400be6"
down_revision: Union[str, None] = "a1d4c07df17e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute("UPDATE recipe SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column("recipe", "created_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe", "created_at")
    # ### end Alembic commands ###
