"""Switch to using RecipeIngredientLink with amount and unit field

Revision ID: 8c67b960ea4c
Revises: 5fbb87540f32
Create Date: 2025-07-26 23:03:04.126310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8c67b960ea4c"
down_revision: Union[str, None] = "5fbb87540f32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipeingredientlink",
        sa.Column("amount", sa.Float(), nullable=False, server_default="1.0"),
    )
    op.add_column(
        "recipeingredientlink",
        sa.Column(
            "unit",
            sqlmodel.sql.sqltypes.AutoString(length=10),
            nullable=False,
            server_default="g",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipeingredientlink", "unit")
    op.drop_column("recipeingredientlink", "amount")
    # ### end Alembic commands ###
