"""convert instruction field back to string from json

Revision ID: 92f0d59bbaab
Revises: 56a47704f2df
Create Date: 2025-07-23 04:49:06.042466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92f0d59bbaab'
down_revision: Union[str, None] = '56a47704f2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hero_age', table_name='hero')
    op.drop_index('ix_hero_name', table_name='hero')
    op.drop_table('hero')
    op.alter_column('recipe', 'instructions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sqlmodel.sql.sqltypes.AutoString(length=9999),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'instructions',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=9999),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('hero',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='hero_pkey')
    )
    op.create_index('ix_hero_name', 'hero', ['name'], unique=False)
    op.create_index('ix_hero_age', 'hero', ['age'], unique=False)
    # ### end Alembic commands ###
