"""instructions field now dict / JSON

Revision ID: aabd10773219
Revises: 0fc55b04baf6
Create Date: 2025-02-19 15:20:33.624067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aabd10773219'
down_revision: Union[str, None] = '0fc55b04baf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('instructions', sa.JSON(), nullable=True))
    op.add_column('recipe', sa.Column('instrutions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'instrutions')
    op.drop_column('recipe', 'instructions')
    # ### end Alembic commands ###
