"""Add image to Recipe

Revision ID: b05211d75551
Revises: 3c8a5681a6b1
Create Date: 2026-01-28 05:25:53.110307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "b05211d75551"
down_revision: Union[str, None] = "3c8a5681a6b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe",
        sa.Column(
            "image", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe", "image")
    # ### end Alembic commands ###
