"""added amount field to PlayerDrinkLink

Revision ID: c17d8a4c6a6c
Revises: f8699487464b
Create Date: 2025-05-18 01:04:39.700926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c17d8a4c6a6c'
down_revision: Union[str, None] = 'f8699487464b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameplayerdrinklink', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameplayerdrinklink', 'amount')
    # ### end Alembic commands ###
