"""add serverings field to recipe model

Revision ID: ce144e53b375
Revises: 4a9dc4a567a3
Create Date: 2025-02-14 00:27:17.278034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce144e53b375'
down_revision: Union[str, None] = '4a9dc4a567a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('servings', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'servings')
    # ### end Alembic commands ###
