"""add_weight_per_piece_to_ingredient

Revision ID: d3a8ba8bdde7
Revises: 1975e36b706a
Create Date: 2025-11-18 09:42:56.099006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3a8ba8bdde7'
down_revision: Union[str, None] = '1975e36b706a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('weight_per_piece', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'weight_per_piece')
    # ### end Alembic commands ###
