"""added title field to the GameSession

Revision ID: e475e4b026d3
Revises: 942d39f57829
Create Date: 2025-04-29 04:00:06.281743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e475e4b026d3'
down_revision: Union[str, None] = '942d39f57829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesession', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamesession', 'title')
    # ### end Alembic commands ###
