"""uncomment amount and unit from RecipeIngredientLink

Revision ID: f7cd03f94e4a
Revises: c51b10eb6c76
Create Date: 2025-01-24 05:19:00.159017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7cd03f94e4a'
down_revision: Union[str, None] = 'c51b10eb6c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipeingredientlink', 'unit')
    op.drop_column('recipeingredientlink', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipeingredientlink', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('recipeingredientlink', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
