"""2nd try on the game

Revision ID: f8699487464b
Revises: 9be9019dea3f
Create Date: 2025-05-04 04:15:25.050584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8699487464b'
down_revision: Union[str, None] = '9be9019dea3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamesession',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameteam',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('game_session_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['gamesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameplayer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('game_session_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['gamesession.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['gameteam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameplayerdrinklink',
    sa.Column('game_player_id', sa.Uuid(), nullable=False),
    sa.Column('drink_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drink.id'], ),
    sa.ForeignKeyConstraint(['game_player_id'], ['gameplayer.id'], ),
    sa.PrimaryKeyConstraint('game_player_id', 'drink_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gameplayerdrinklink')
    op.drop_table('gameplayer')
    op.drop_table('gameteam')
    op.drop_table('gamesession')
    op.drop_table('drink')
    # ### end Alembic commands ###
