// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login-login_access_token'
} as const;

export const Body_recipes_upload_recipe_imageSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: [
        'file'
    ],
    title: 'Body_recipes-upload_recipe_image'
} as const;

export const DrinkCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'DrinkCreate'
} as const;

export const DrinkPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'name',
        'id'
    ],
    title: 'DrinkPublic'
} as const;

export const GamePlayerSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        game_session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Game Session Id'
        },
        team_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Team Id'
        }
    },
    type: 'object',
    required: [
        'name',
        'game_session_id'
    ],
    title: 'GamePlayer',
    description: 'Game player model\n\nShould have a name, a team and a list of drinks (many to many relationship)'
} as const;

export const GamePlayerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        team_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Team Id'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'GamePlayerCreate',
    description: 'Create class for game player'
} as const;

export const GamePlayerDrinkLinkCreateSchema = {
    properties: {
        drink_id: {
            type: 'string',
            format: 'uuid',
            title: 'Drink Id'
        },
        amount: {
            type: 'integer',
            minimum: 0,
            title: 'Amount',
            description: 'How many of this drink the player has consumed',
            default: 1
        }
    },
    type: 'object',
    required: [
        'drink_id'
    ],
    title: 'GamePlayerDrinkLinkCreate',
    description: 'Create class for GamePlayerDrinkLink'
} as const;

export const GamePlayerDrinkLinkPublicSchema = {
    properties: {
        amount: {
            type: 'integer',
            title: 'Amount'
        },
        drink: {
            $ref: '#/components/schemas/DrinkPublic'
        }
    },
    type: 'object',
    required: [
        'amount',
        'drink'
    ],
    title: 'GamePlayerDrinkLinkPublic',
    description: 'Public class for GamePlayerDrinkLink'
} as const;

export const GamePlayerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        game_session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Game Session Id'
        },
        team_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Team Id'
        },
        team: {
            anyOf: [
                {
                    $ref: '#/components/schemas/GameTeamPlayerPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        drink_links: {
            items: {
                $ref: '#/components/schemas/GamePlayerDrinkLinkPublic'
            },
            type: 'array',
            title: 'Drink Links'
        }
    },
    type: 'object',
    required: [
        'name',
        'id',
        'game_session_id',
        'drink_links'
    ],
    title: 'GamePlayerPublic',
    description: 'Public class for game player'
} as const;

export const GamePlayerUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        team_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Team Id'
        },
        drinks: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/GamePlayerDrinkLinkCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Drinks'
        }
    },
    type: 'object',
    title: 'GamePlayerUpdate',
    description: 'Update class for game player, can update name and team, can not change game session'
} as const;

export const GameSessionCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        teams: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/GameTeamCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Teams'
        }
    },
    type: 'object',
    required: [
        'title'
    ],
    title: 'GameSessionCreate'
} as const;

export const GameSessionPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        owner: {
            $ref: '#/components/schemas/UserPublic'
        },
        players: {
            items: {
                $ref: '#/components/schemas/GamePlayerPublic'
            },
            type: 'array',
            title: 'Players'
        },
        teams: {
            items: {
                $ref: '#/components/schemas/GameTeamPublic'
            },
            type: 'array',
            title: 'Teams'
        }
    },
    type: 'object',
    required: [
        'title',
        'id',
        'created_at',
        'owner',
        'players',
        'teams'
    ],
    title: 'GameSessionPublic',
    description: 'Game session model\n\nShould have an owner (user) and a list of players and their information (scores etc.)'
} as const;

export const GameTeamCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'GameTeamCreate'
} as const;

export const GameTeamPlayerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'GameTeamPlayerPublic'
} as const;

export const GameTeamPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        players: {
            items: {
                $ref: '#/components/schemas/GamePlayer'
            },
            type: 'array',
            title: 'Players'
        },
        game_session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Game Session Id'
        }
    },
    type: 'object',
    required: [
        'name',
        'id',
        'players',
        'game_session_id'
    ],
    title: 'GameTeamPublic',
    description: 'Public class for game team'
} as const;

export const HTTPExceptionDetailSchema = {
    properties: {
        detail: {
            type: 'string',
            title: 'Detail'
        }
    },
    type: 'object',
    required: [
        'detail'
    ],
    title: 'HTTPExceptionDetail'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IngredientCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        calories: {
            type: 'integer',
            minimum: 0,
            title: 'Calories',
            description: 'Calories per 100g of the ingredient',
            default: 0
        },
        carbohydrates: {
            type: 'number',
            minimum: 0,
            title: 'Carbohydrates',
            description: 'Carbohydrates per 100g of the ingredient in grams',
            default: 0
        },
        fat: {
            type: 'number',
            minimum: 0,
            title: 'Fat',
            description: 'Fat per 100g of the ingredient in grams',
            default: 0
        },
        protein: {
            type: 'number',
            minimum: 0,
            title: 'Protein',
            description: 'Protein per 100g of the ingredient in grams',
            default: 0
        },
        weight_per_piece: {
            type: 'integer',
            minimum: 0,
            title: 'Weight Per Piece',
            description: 'Average weight per piece in grams (used when unit is \'pcs\')',
            default: 100
        }
    },
    type: 'object',
    required: [
        'title'
    ],
    title: 'IngredientCreate'
} as const;

export const IngredientPublicSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        calories: {
            type: 'integer',
            title: 'Calories'
        },
        carbohydrates: {
            type: 'number',
            title: 'Carbohydrates'
        },
        fat: {
            type: 'number',
            title: 'Fat'
        },
        protein: {
            type: 'number',
            title: 'Protein'
        },
        weight_per_piece: {
            type: 'integer',
            title: 'Weight Per Piece'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'title',
        'calories',
        'carbohydrates',
        'fat',
        'protein',
        'weight_per_piece',
        'id'
    ],
    title: 'IngredientPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'token',
        'new_password'
    ],
    title: 'NewPassword'
} as const;

export const RecipeSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        instructions: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 9999
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instructions'
        },
        servings: {
            type: 'integer',
            title: 'Servings',
            default: 1
        },
        image: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            default: '2026-02-26T14:37:28.085724Z'
        }
    },
    type: 'object',
    required: [
        'title',
        'owner_id'
    ],
    title: 'Recipe',
    description: 'Recipe model\n\nShould have an owner and a list of ingredients. However a recipe for every ingredints, the ingredient should also have an amount of that ingredient and the unit of the amount'
} as const;

export const RecipeCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        instructions: {
            type: 'string',
            title: 'Instructions'
        },
        servings: {
            type: 'integer',
            title: 'Servings'
        },
        image: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        ingredients: {
            items: {
                $ref: '#/components/schemas/RecipeIngredientLinkCreate'
            },
            type: 'array',
            title: 'Ingredients'
        },
        sub_recipes: {
            items: {
                $ref: '#/components/schemas/RecipeSubRecipeLinkCreate'
            },
            type: 'array',
            title: 'Sub Recipes',
            default: []
        }
    },
    type: 'object',
    required: [
        'title',
        'instructions',
        'servings',
        'ingredients'
    ],
    title: 'RecipeCreate'
} as const;

export const RecipeIngredientLinkCreateSchema = {
    properties: {
        ingredient_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ingredient Id'
        },
        amount: {
            type: 'number',
            minimum: 0,
            title: 'Amount',
            description: 'Amount of the ingredient in the recipe',
            default: 1
        },
        unit: {
            type: 'string',
            maxLength: 10,
            title: 'Unit',
            description: 'Unit of the amount, e.g. g, ml, pcs, etc.',
            default: 'g'
        }
    },
    type: 'object',
    required: [
        'ingredient_id'
    ],
    title: 'RecipeIngredientLinkCreate',
    description: 'Create a new recipe ingredient link.'
} as const;

export const RecipeIngredientLinkPublicSchema = {
    properties: {
        ingredient: {
            $ref: '#/components/schemas/IngredientPublic'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        unit: {
            type: 'string',
            maxLength: 10,
            title: 'Unit',
            description: 'Unit of the amount, e.g. g, ml, pcs, etc.',
            default: 'g'
        }
    },
    type: 'object',
    required: [
        'ingredient',
        'amount'
    ],
    title: 'RecipeIngredientLinkPublic',
    description: 'Public class for recipe ingredient link.'
} as const;

export const RecipeIngredientSourcePublicSchema = {
    properties: {
        recipe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Recipe Id'
        },
        recipe_title: {
            type: 'string',
            title: 'Recipe Title'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        unit: {
            type: 'string',
            maxLength: 10,
            title: 'Unit',
            description: 'Unit of the amount, e.g. g, ml, pcs, etc.'
        },
        is_main_recipe: {
            type: 'boolean',
            title: 'Is Main Recipe',
            description: 'True when the source is the currently viewed recipe.'
        }
    },
    type: 'object',
    required: [
        'recipe_id',
        'recipe_title',
        'amount',
        'unit',
        'is_main_recipe'
    ],
    title: 'RecipeIngredientSourcePublic'
} as const;

export const RecipeIngredientTotalPublicSchema = {
    properties: {
        ingredient_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ingredient Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        unit: {
            type: 'string',
            maxLength: 10,
            title: 'Unit',
            description: 'Unit of the amount, e.g. g, ml, pcs, etc.'
        },
        grams: {
            type: 'number',
            title: 'Grams',
            description: 'Total ingredient amount converted to grams for nutrition calculations.'
        },
        calories: {
            type: 'number',
            title: 'Calories',
            description: 'Calories contributed by this aggregated ingredient amount.'
        },
        carbohydrates: {
            type: 'number',
            title: 'Carbohydrates',
            description: 'Carbohydrates (g) contributed by this aggregated ingredient amount.'
        },
        fat: {
            type: 'number',
            title: 'Fat',
            description: 'Fat (g) contributed by this aggregated ingredient amount.'
        },
        protein: {
            type: 'number',
            title: 'Protein',
            description: 'Protein (g) contributed by this aggregated ingredient amount.'
        },
        sources: {
            items: {
                $ref: '#/components/schemas/RecipeIngredientSourcePublic'
            },
            type: 'array',
            title: 'Sources'
        },
        source_count: {
            type: 'integer',
            title: 'Source Count',
            readOnly: true
        },
        has_overlap: {
            type: 'boolean',
            title: 'Has Overlap',
            readOnly: true
        }
    },
    type: 'object',
    required: [
        'ingredient_id',
        'title',
        'amount',
        'unit',
        'grams',
        'calories',
        'carbohydrates',
        'fat',
        'protein',
        'sources',
        'source_count',
        'has_overlap'
    ],
    title: 'RecipeIngredientTotalPublic'
} as const;

export const RecipePublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        instructions: {
            type: 'string',
            title: 'Instructions'
        },
        servings: {
            type: 'integer',
            title: 'Servings'
        },
        image: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner: {
            $ref: '#/components/schemas/UserPublic'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        ingredient_links: {
            items: {
                $ref: '#/components/schemas/RecipeIngredientLinkPublic'
            },
            type: 'array',
            title: 'Ingredient Links'
        },
        sub_recipe_links: {
            items: {
                $ref: '#/components/schemas/RecipeSubRecipeLinkPublic'
            },
            type: 'array',
            title: 'Sub Recipe Links',
            default: []
        },
        total_ingredients: {
            items: {
                $ref: '#/components/schemas/RecipeIngredientTotalPublic'
            },
            type: 'array',
            title: 'Total Ingredients'
        },
        total_calories: {
            type: 'integer',
            title: 'Total Calories',
            description: 'Calculate total calories for the entire recipe based on ingredients and their amounts.',
            readOnly: true
        },
        calories_per_serving: {
            type: 'integer',
            title: 'Calories Per Serving',
            description: 'Calculate calories per serving.',
            readOnly: true
        },
        total_carbohydrates: {
            type: 'number',
            title: 'Total Carbohydrates',
            description: 'Calculate total carbohydrates for the entire recipe in grams.',
            readOnly: true
        },
        total_fat: {
            type: 'number',
            title: 'Total Fat',
            description: 'Calculate total fat for the entire recipe in grams.',
            readOnly: true
        },
        total_protein: {
            type: 'number',
            title: 'Total Protein',
            description: 'Calculate total protein for the entire recipe in grams.',
            readOnly: true
        },
        carbohydrates_per_serving: {
            type: 'number',
            title: 'Carbohydrates Per Serving',
            description: 'Calculate carbohydrates per serving in grams.',
            readOnly: true
        },
        fat_per_serving: {
            type: 'number',
            title: 'Fat Per Serving',
            description: 'Calculate fat per serving in grams.',
            readOnly: true
        },
        protein_per_serving: {
            type: 'number',
            title: 'Protein Per Serving',
            description: 'Calculate protein per serving in grams.',
            readOnly: true
        },
        calculated_weight: {
            type: 'integer',
            title: 'Calculated Weight',
            description: 'The calculated weight of the recipe based on the ingredients and their amounts. Returns the total weight in grams.',
            readOnly: true
        },
        calories_per_100g: {
            type: 'integer',
            title: 'Calories Per 100G',
            description: 'Calculate calories per 100g of the recipe.',
            readOnly: true
        }
    },
    type: 'object',
    required: [
        'title',
        'instructions',
        'servings',
        'id',
        'owner',
        'created_at',
        'ingredient_links',
        'total_ingredients',
        'total_calories',
        'calories_per_serving',
        'total_carbohydrates',
        'total_fat',
        'total_protein',
        'carbohydrates_per_serving',
        'fat_per_serving',
        'protein_per_serving',
        'calculated_weight',
        'calories_per_100g'
    ],
    title: 'RecipePublic'
} as const;

export const RecipeSubRecipeLinkCreateSchema = {
    properties: {
        sub_recipe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Sub Recipe Id'
        },
        scale_factor: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Scale Factor',
            description: 'Multiplier applied to the linked sub-recipe. Example: 0.25 means a quarter of the recipe.',
            default: 1
        }
    },
    type: 'object',
    required: [
        'sub_recipe_id'
    ],
    title: 'RecipeSubRecipeLinkCreate'
} as const;

export const RecipeSubRecipeLinkPublicSchema = {
    properties: {
        sub_recipe: {
            $ref: '#/components/schemas/RecipeSubRecipePublic'
        },
        scale_factor: {
            type: 'number',
            title: 'Scale Factor'
        },
        scaled_servings: {
            type: 'number',
            title: 'Scaled Servings',
            readOnly: true
        }
    },
    type: 'object',
    required: [
        'sub_recipe',
        'scale_factor',
        'scaled_servings'
    ],
    title: 'RecipeSubRecipeLinkPublic'
} as const;

export const RecipeSubRecipePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        servings: {
            type: 'integer',
            title: 'Servings'
        },
        image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        }
    },
    type: 'object',
    required: [
        'id',
        'title',
        'servings'
    ],
    title: 'RecipeSubRecipePublic'
} as const;

export const RefreshRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: [
        'refresh_token'
    ],
    title: 'RefreshRequest'
} as const;

export const RoleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        scopes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Scopes',
            default: []
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'RoleCreate'
} as const;

export const RolePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        scopes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Scopes'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'scopes'
    ],
    title: 'RolePublic'
} as const;

export const RoleUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        scopes: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scopes'
        }
    },
    type: 'object',
    title: 'RoleUpdate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'Bearer'
        },
        refresh_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'current_password',
        'new_password'
    ],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserCreate'
} as const;

export const UserMePublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        scopes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Scopes'
        }
    },
    type: 'object',
    required: [
        'email',
        'id',
        'scopes'
    ],
    title: 'UserMePublic'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'email',
        'id'
    ],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UserWithPermissionsPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        roles: {
            items: {
                $ref: '#/components/schemas/RolePublic'
            },
            type: 'array',
            title: 'Roles'
        },
        custom_scopes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Custom Scopes'
        },
        effective_scopes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Effective Scopes'
        }
    },
    type: 'object',
    required: [
        'email',
        'id',
        'roles',
        'custom_scopes',
        'effective_scopes'
    ],
    title: 'UserWithPermissionsPublic'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersPublic'
} as const;

export const UsersWithPermissionsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserWithPermissionsPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersWithPermissionsPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const RecipeIngredientTotalPublicWritableSchema = {
    properties: {
        ingredient_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ingredient Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        unit: {
            type: 'string',
            maxLength: 10,
            title: 'Unit',
            description: 'Unit of the amount, e.g. g, ml, pcs, etc.'
        },
        grams: {
            type: 'number',
            title: 'Grams',
            description: 'Total ingredient amount converted to grams for nutrition calculations.'
        },
        calories: {
            type: 'number',
            title: 'Calories',
            description: 'Calories contributed by this aggregated ingredient amount.'
        },
        carbohydrates: {
            type: 'number',
            title: 'Carbohydrates',
            description: 'Carbohydrates (g) contributed by this aggregated ingredient amount.'
        },
        fat: {
            type: 'number',
            title: 'Fat',
            description: 'Fat (g) contributed by this aggregated ingredient amount.'
        },
        protein: {
            type: 'number',
            title: 'Protein',
            description: 'Protein (g) contributed by this aggregated ingredient amount.'
        },
        sources: {
            items: {
                $ref: '#/components/schemas/RecipeIngredientSourcePublic'
            },
            type: 'array',
            title: 'Sources'
        }
    },
    type: 'object',
    required: [
        'ingredient_id',
        'title',
        'amount',
        'unit',
        'grams',
        'calories',
        'carbohydrates',
        'fat',
        'protein',
        'sources'
    ],
    title: 'RecipeIngredientTotalPublic'
} as const;

export const RecipePublicWritableSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        instructions: {
            type: 'string',
            title: 'Instructions'
        },
        servings: {
            type: 'integer',
            title: 'Servings'
        },
        image: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner: {
            $ref: '#/components/schemas/UserPublic'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        ingredient_links: {
            items: {
                $ref: '#/components/schemas/RecipeIngredientLinkPublic'
            },
            type: 'array',
            title: 'Ingredient Links'
        },
        sub_recipe_links: {
            items: {
                $ref: '#/components/schemas/RecipeSubRecipeLinkPublicWritable'
            },
            type: 'array',
            title: 'Sub Recipe Links',
            default: []
        },
        total_ingredients: {
            items: {
                $ref: '#/components/schemas/RecipeIngredientTotalPublicWritable'
            },
            type: 'array',
            title: 'Total Ingredients'
        }
    },
    type: 'object',
    required: [
        'title',
        'instructions',
        'servings',
        'id',
        'owner',
        'created_at',
        'ingredient_links',
        'total_ingredients'
    ],
    title: 'RecipePublic'
} as const;

export const RecipeSubRecipeLinkPublicWritableSchema = {
    properties: {
        sub_recipe: {
            $ref: '#/components/schemas/RecipeSubRecipePublic'
        },
        scale_factor: {
            type: 'number',
            title: 'Scale Factor'
        }
    },
    type: 'object',
    required: [
        'sub_recipe',
        'scale_factor'
    ],
    title: 'RecipeSubRecipeLinkPublic'
} as const;
