// This file is auto-generated by @hey-api/openapi-ts

import type { DeleteRecipesByRecipeIdResponse, GetGameByGameSessionIdResponse, GetGameResponse, GetRecipesByRecipeIdResponse, GetRecipesResponse, PatchRecipesByRecipeIdResponse, PostGameResponse, PostRecipesResponse } from './types.gen';

const recipePublicSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    return data;
};

export const getRecipesResponseTransformer = async (data: any): Promise<GetRecipesResponse> => {
    data = data.map((item: any) => recipePublicSchemaResponseTransformer(item));
    return data;
};

export const postRecipesResponseTransformer = async (data: any): Promise<PostRecipesResponse> => {
    data = recipePublicSchemaResponseTransformer(data);
    return data;
};

const recipeSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    return data;
};

export const deleteRecipesByRecipeIdResponseTransformer = async (data: any): Promise<DeleteRecipesByRecipeIdResponse> => {
    data = recipeSchemaResponseTransformer(data);
    return data;
};

export const getRecipesByRecipeIdResponseTransformer = async (data: any): Promise<GetRecipesByRecipeIdResponse> => {
    data = recipePublicSchemaResponseTransformer(data);
    return data;
};

export const patchRecipesByRecipeIdResponseTransformer = async (data: any): Promise<PatchRecipesByRecipeIdResponse> => {
    data = recipePublicSchemaResponseTransformer(data);
    return data;
};

const gameSessionPublicSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    return data;
};

export const getGameResponseTransformer = async (data: any): Promise<GetGameResponse> => {
    data = data.map((item: any) => gameSessionPublicSchemaResponseTransformer(item));
    return data;
};

export const postGameResponseTransformer = async (data: any): Promise<PostGameResponse> => {
    data = gameSessionPublicSchemaResponseTransformer(data);
    return data;
};

export const getGameByGameSessionIdResponseTransformer = async (data: any): Promise<GetGameByGameSessionIdResponse> => {
    data = gameSessionPublicSchemaResponseTransformer(data);
    return data;
};
