// This file is auto-generated by @hey-api/openapi-ts

import type { DeleteNutritionEntriesByEntryIdResponse, DeleteProductsByProductIdResponse, DeleteRecipesByRecipeIdResponse, GetAnalyticsAdminSummaryResponse, GetGameByGameSessionIdResponse, GetGameResponse, GetNutritionCatalogResponse, GetNutritionCommonEntriesResponse, GetNutritionDayByLogDateResponse, GetProductsByProductIdResponse, GetProductsResponse, GetRecipesByRecipeIdResponse, GetRecipesResponse, PatchNutritionEntriesByEntryIdResponse, PatchProductsByProductIdResponse, PatchRecipesByRecipeIdResponse, PostGameResponse, PostNutritionEntriesBatchResponse, PostNutritionEntriesResponse, PostProductsResponse, PostRecipesResponse, PutNutritionEntriesByEntryIdResponse } from './types.gen';

const recipePublicSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    return data;
};

export const getRecipesResponseTransformer = async (data: any): Promise<GetRecipesResponse> => {
    data = data.map((item: any) => recipePublicSchemaResponseTransformer(item));
    return data;
};

export const postRecipesResponseTransformer = async (data: any): Promise<PostRecipesResponse> => {
    data = recipePublicSchemaResponseTransformer(data);
    return data;
};

const recipeSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    return data;
};

export const deleteRecipesByRecipeIdResponseTransformer = async (data: any): Promise<DeleteRecipesByRecipeIdResponse> => {
    data = recipeSchemaResponseTransformer(data);
    return data;
};

export const getRecipesByRecipeIdResponseTransformer = async (data: any): Promise<GetRecipesByRecipeIdResponse> => {
    data = recipePublicSchemaResponseTransformer(data);
    return data;
};

export const patchRecipesByRecipeIdResponseTransformer = async (data: any): Promise<PatchRecipesByRecipeIdResponse> => {
    data = recipePublicSchemaResponseTransformer(data);
    return data;
};

const gameSessionPublicSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    return data;
};

export const getGameResponseTransformer = async (data: any): Promise<GetGameResponse> => {
    data = data.map((item: any) => gameSessionPublicSchemaResponseTransformer(item));
    return data;
};

export const postGameResponseTransformer = async (data: any): Promise<PostGameResponse> => {
    data = gameSessionPublicSchemaResponseTransformer(data);
    return data;
};

export const getGameByGameSessionIdResponseTransformer = async (data: any): Promise<GetGameByGameSessionIdResponse> => {
    data = gameSessionPublicSchemaResponseTransformer(data);
    return data;
};

const analyticsDailyCountPublicSchemaResponseTransformer = (data: any) => {
    data.date = new Date(data.date);
    return data;
};

const analyticsSummaryPublicSchemaResponseTransformer = (data: any) => {
    data.generated_at = new Date(data.generated_at);
    data.daily_last_7_days = data.daily_last_7_days.map((item: any) => analyticsDailyCountPublicSchemaResponseTransformer(item));
    return data;
};

export const getAnalyticsAdminSummaryResponseTransformer = async (data: any): Promise<GetAnalyticsAdminSummaryResponse> => {
    data = analyticsSummaryPublicSchemaResponseTransformer(data);
    return data;
};

const productPublicSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

export const getProductsResponseTransformer = async (data: any): Promise<GetProductsResponse> => {
    data = data.map((item: any) => productPublicSchemaResponseTransformer(item));
    return data;
};

export const postProductsResponseTransformer = async (data: any): Promise<PostProductsResponse> => {
    data = productPublicSchemaResponseTransformer(data);
    return data;
};

export const deleteProductsByProductIdResponseTransformer = async (data: any): Promise<DeleteProductsByProductIdResponse> => {
    data = productPublicSchemaResponseTransformer(data);
    return data;
};

export const getProductsByProductIdResponseTransformer = async (data: any): Promise<GetProductsByProductIdResponse> => {
    data = productPublicSchemaResponseTransformer(data);
    return data;
};

export const patchProductsByProductIdResponseTransformer = async (data: any): Promise<PatchProductsByProductIdResponse> => {
    data = productPublicSchemaResponseTransformer(data);
    return data;
};

const nutritionEntryPublicSchemaResponseTransformer = (data: any) => {
    data.log_date = new Date(data.log_date);
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

const nutritionMealGroupPublicSchemaResponseTransformer = (data: any) => {
    data.entries = data.entries.map((item: any) => nutritionEntryPublicSchemaResponseTransformer(item));
    return data;
};

const nutritionDayPublicSchemaResponseTransformer = (data: any) => {
    data.log_date = new Date(data.log_date);
    data.groups = data.groups.map((item: any) => nutritionMealGroupPublicSchemaResponseTransformer(item));
    return data;
};

export const getNutritionDayByLogDateResponseTransformer = async (data: any): Promise<GetNutritionDayByLogDateResponse> => {
    data = nutritionDayPublicSchemaResponseTransformer(data);
    return data;
};

const nutritionCatalogPublicSchemaResponseTransformer = (data: any) => {
    data.products = data.products.map((item: any) => productPublicSchemaResponseTransformer(item));
    return data;
};

export const getNutritionCatalogResponseTransformer = async (data: any): Promise<GetNutritionCatalogResponse> => {
    data = nutritionCatalogPublicSchemaResponseTransformer(data);
    return data;
};

const nutritionCommonEntryPublicSchemaResponseTransformer = (data: any) => {
    data.last_used_at = new Date(data.last_used_at);
    return data;
};

const nutritionCommonEntriesPublicSchemaResponseTransformer = (data: any) => {
    data.entries = data.entries.map((item: any) => nutritionCommonEntryPublicSchemaResponseTransformer(item));
    return data;
};

export const getNutritionCommonEntriesResponseTransformer = async (data: any): Promise<GetNutritionCommonEntriesResponse> => {
    data = nutritionCommonEntriesPublicSchemaResponseTransformer(data);
    return data;
};

export const postNutritionEntriesResponseTransformer = async (data: any): Promise<PostNutritionEntriesResponse> => {
    data = nutritionEntryPublicSchemaResponseTransformer(data);
    return data;
};

const nutritionEntryBatchPublicSchemaResponseTransformer = (data: any) => {
    data.entries = data.entries.map((item: any) => nutritionEntryPublicSchemaResponseTransformer(item));
    return data;
};

export const postNutritionEntriesBatchResponseTransformer = async (data: any): Promise<PostNutritionEntriesBatchResponse> => {
    data = nutritionEntryBatchPublicSchemaResponseTransformer(data);
    return data;
};

export const deleteNutritionEntriesByEntryIdResponseTransformer = async (data: any): Promise<DeleteNutritionEntriesByEntryIdResponse> => {
    data = nutritionEntryPublicSchemaResponseTransformer(data);
    return data;
};

export const patchNutritionEntriesByEntryIdResponseTransformer = async (data: any): Promise<PatchNutritionEntriesByEntryIdResponse> => {
    data = nutritionEntryPublicSchemaResponseTransformer(data);
    return data;
};

export const putNutritionEntriesByEntryIdResponseTransformer = async (data: any): Promise<PutNutritionEntriesByEntryIdResponse> => {
    data = nutritionEntryPublicSchemaResponseTransformer(data);
    return data;
};
