// This file is auto-generated by @hey-api/openapi-ts

import type {
    GetGameByGameSessionIdResponse,
    GetGameResponse,
    PostGameResponse
} from "./types.gen";

const gameSessionPublicSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    return data;
};

export const getGameResponseTransformer = async (data: any): Promise<GetGameResponse> => {
    data = data.map((item: any) => gameSessionPublicSchemaResponseTransformer(item));
    return data;
};

export const postGameResponseTransformer = async (data: any): Promise<PostGameResponse> => {
    data = gameSessionPublicSchemaResponseTransformer(data);
    return data;
};

export const getGameByGameSessionIdResponseTransformer = async (
    data: any
): Promise<GetGameByGameSessionIdResponse> => {
    data = gameSessionPublicSchemaResponseTransformer(data);
    return data;
};
