// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_recipes-upload_recipe_image
 */
export type BodyRecipesUploadRecipeImage = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * DrinkCreate
 */
export type DrinkCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * DrinkPublic
 */
export type DrinkPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
};

/**
 * GamePlayer
 *
 * Game player model
 *
 * Should have a name, a team and a list of drinks (many to many relationship)
 */
export type GamePlayer = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id?: string;
    /**
     * Game Session Id
     */
    game_session_id: string;
    /**
     * Team Id
     */
    team_id?: string | null;
};

/**
 * GamePlayerCreate
 *
 * Create class for game player
 */
export type GamePlayerCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Team Id
     */
    team_id?: string | null;
};

/**
 * GamePlayerDrinkLinkCreate
 *
 * Create class for GamePlayerDrinkLink
 */
export type GamePlayerDrinkLinkCreate = {
    /**
     * Drink Id
     */
    drink_id: string;
    /**
     * Amount
     *
     * How many of this drink the player has consumed
     */
    amount?: number;
};

/**
 * GamePlayerDrinkLinkPublic
 *
 * Public class for GamePlayerDrinkLink
 */
export type GamePlayerDrinkLinkPublic = {
    /**
     * Amount
     */
    amount: number;
    drink: DrinkPublic;
};

/**
 * GamePlayerPublic
 *
 * Public class for game player
 */
export type GamePlayerPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Game Session Id
     */
    game_session_id: string;
    /**
     * Team Id
     */
    team_id?: string | null;
    team?: GameTeamPlayerPublic | null;
    /**
     * Drink Links
     */
    drink_links: Array<GamePlayerDrinkLinkPublic>;
};

/**
 * GamePlayerUpdate
 *
 * Update class for game player, can update name and team, can not change game session
 */
export type GamePlayerUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Team Id
     */
    team_id?: string | null;
    /**
     * Drinks
     */
    drinks?: Array<GamePlayerDrinkLinkCreate> | null;
};

/**
 * GameSessionCreate
 */
export type GameSessionCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Teams
     */
    teams?: Array<GameTeamCreate> | null;
};

/**
 * GameSessionPublic
 *
 * Game session model
 *
 * Should have an owner (user) and a list of players and their information (scores etc.)
 */
export type GameSessionPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: Date;
    owner: UserPublic;
    /**
     * Players
     */
    players: Array<GamePlayerPublic>;
    /**
     * Teams
     */
    teams: Array<GameTeamPublic>;
};

/**
 * GameTeamCreate
 */
export type GameTeamCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * GameTeamPlayerPublic
 */
export type GameTeamPlayerPublic = {
    /**
     * Name
     */
    name: string;
};

/**
 * GameTeamPublic
 *
 * Public class for game team
 */
export type GameTeamPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Players
     */
    players: Array<GamePlayer>;
    /**
     * Game Session Id
     */
    game_session_id: string;
};

/**
 * HTTPExceptionDetail
 */
export type HttpExceptionDetail = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IngredientCreate
 */
export type IngredientCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Calories
     *
     * Calories per 100g of the ingredient
     */
    calories?: number;
    /**
     * Weight Per Piece
     *
     * Average weight per piece in grams (used when unit is 'pcs')
     */
    weight_per_piece?: number;
};

/**
 * IngredientPublic
 */
export type IngredientPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Calories
     *
     * Calories per 100g of the ingredient
     */
    calories?: number;
    /**
     * Weight Per Piece
     *
     * Average weight per piece in grams (used when unit is 'pcs')
     */
    weight_per_piece?: number;
    /**
     * Id
     */
    id: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * Recipe
 *
 * Recipe model
 *
 * Should have an owner and a list of ingredients. However a recipe for every ingredints, the ingredient should also have an amount of that ingredient and the unit of the amount
 */
export type Recipe = {
    /**
     * Title
     */
    title: string;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Servings
     */
    servings?: number;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Id
     */
    id?: string;
    /**
     * Owner Id
     */
    owner_id: string;
};

/**
 * RecipeCreate
 */
export type RecipeCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Servings
     */
    servings?: number;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Ingredients
     */
    ingredients: Array<RecipeIngredientLinkCreate>;
};

/**
 * RecipeIngredientLinkCreate
 *
 * Create a new recipe ingredient link.
 */
export type RecipeIngredientLinkCreate = {
    /**
     * Ingredient Id
     */
    ingredient_id: string;
    /**
     * Amount
     *
     * Amount of the ingredient in the recipe
     */
    amount?: number;
    /**
     * Unit
     *
     * Unit of the amount, e.g. g, ml, pcs, etc.
     */
    unit?: string;
};

/**
 * RecipeIngredientLinkPublic
 *
 * Public class for recipe ingredient link.
 */
export type RecipeIngredientLinkPublic = {
    ingredient: IngredientPublic;
    /**
     * Amount
     */
    amount: number;
    /**
     * Unit
     *
     * Unit of the amount, e.g. g, ml, pcs, etc.
     */
    unit?: string;
};

/**
 * RecipePublic
 */
export type RecipePublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Servings
     */
    servings?: number;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Id
     */
    id: string;
    owner: UserPublic;
    /**
     * Ingredient Links
     */
    ingredient_links: Array<RecipeIngredientLinkPublic>;
    /**
     * Total Calories
     *
     * Calculate total calories for the entire recipe based on ingredients and their amounts.
     */
    readonly total_calories: number;
    /**
     * Calories Per Serving
     *
     * Calculate calories per serving.
     */
    readonly calories_per_serving: number;
    /**
     * Calculated Weight
     *
     * The calculated weight of the recipe based on the ingredients and their amounts. Returns the total weight in grams.
     */
    readonly calculated_weight: number;
    /**
     * Calories Per 100G
     *
     * Calculate calories per 100g of the recipe.
     */
    readonly calories_per_100g: number;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RoleCreate
 */
export type RoleCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Scopes
     */
    scopes?: Array<string>;
};

/**
 * RolePublic
 */
export type RolePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Scopes
     */
    scopes: Array<string>;
};

/**
 * RoleUpdate
 */
export type RoleUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Scopes
     */
    scopes?: Array<string> | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Refresh Token
     */
    refresh_token?: string | null;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserMePublic
 */
export type UserMePublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UserWithPermissionsPublic
 */
export type UserWithPermissionsPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Roles
     */
    roles: Array<RolePublic>;
    /**
     * Custom Scopes
     */
    custom_scopes: Array<string>;
    /**
     * Effective Scopes
     */
    effective_scopes: Array<string>;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * UsersWithPermissionsPublic
 */
export type UsersWithPermissionsPublic = {
    /**
     * Data
     */
    data: Array<UserWithPermissionsPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * RecipePublic
 */
export type RecipePublicWritable = {
    /**
     * Title
     */
    title: string;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Servings
     */
    servings?: number;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Id
     */
    id: string;
    owner: UserPublic;
    /**
     * Ingredient Links
     */
    ingredient_links: Array<RecipeIngredientLinkPublic>;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/users/';
};

export type GetUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users/';
};

export type PostUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostUsersError = PostUsersErrors[keyof PostUsersErrors];

export type PostUsersResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type GetUsersWithPermissionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/users/with-permissions';
};

export type GetUsersWithPermissionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersWithPermissionsError = GetUsersWithPermissionsErrors[keyof GetUsersWithPermissionsErrors];

export type GetUsersWithPermissionsResponses = {
    /**
     * Successful Response
     */
    200: UsersWithPermissionsPublic;
};

export type GetUsersWithPermissionsResponse = GetUsersWithPermissionsResponses[keyof GetUsersWithPermissionsResponses];

export type DeleteUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type DeleteUsersMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUsersMeResponse = DeleteUsersMeResponses[keyof DeleteUsersMeResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeErrors = {
    /**
     * Unauthorized
     */
    401: HttpExceptionDetail;
};

export type GetUsersMeError = GetUsersMeErrors[keyof GetUsersMeErrors];

export type GetUsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserMePublic;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type PatchUsersMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type PatchUsersMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchUsersMeError = PatchUsersMeErrors[keyof PatchUsersMeErrors];

export type PatchUsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PatchUsersMeResponse = PatchUsersMeResponses[keyof PatchUsersMeResponses];

export type PatchUsersMePasswordData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/users/me/password';
};

export type PatchUsersMePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchUsersMePasswordError = PatchUsersMePasswordErrors[keyof PatchUsersMePasswordErrors];

export type PatchUsersMePasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PatchUsersMePasswordResponse = PatchUsersMePasswordResponses[keyof PatchUsersMePasswordResponses];

export type PostUsersSignupData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/users/signup';
};

export type PostUsersSignupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostUsersSignupError = PostUsersSignupErrors[keyof PostUsersSignupErrors];

export type PostUsersSignupResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PostUsersSignupResponse = PostUsersSignupResponses[keyof PostUsersSignupResponses];

export type DeleteUsersByUserIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUsersByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUsersByUserIdError = DeleteUsersByUserIdErrors[keyof DeleteUsersByUserIdErrors];

export type DeleteUsersByUserIdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUsersByUserIdResponse = DeleteUsersByUserIdResponses[keyof DeleteUsersByUserIdResponses];

export type GetUsersByUserIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUsersByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersByUserIdError = GetUsersByUserIdErrors[keyof GetUsersByUserIdErrors];

export type GetUsersByUserIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetUsersByUserIdResponse = GetUsersByUserIdResponses[keyof GetUsersByUserIdResponses];

export type PatchUsersByUserIdData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type PatchUsersByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchUsersByUserIdError = PatchUsersByUserIdErrors[keyof PatchUsersByUserIdErrors];

export type PatchUsersByUserIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PatchUsersByUserIdResponse = PatchUsersByUserIdResponses[keyof PatchUsersByUserIdResponses];

export type DeleteUsersByUserIdRolesByRoleIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/users/{user_id}/roles/{role_id}';
};

export type DeleteUsersByUserIdRolesByRoleIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUsersByUserIdRolesByRoleIdError = DeleteUsersByUserIdRolesByRoleIdErrors[keyof DeleteUsersByUserIdRolesByRoleIdErrors];

export type DeleteUsersByUserIdRolesByRoleIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type DeleteUsersByUserIdRolesByRoleIdResponse = DeleteUsersByUserIdRolesByRoleIdResponses[keyof DeleteUsersByUserIdRolesByRoleIdResponses];

export type PostUsersByUserIdRolesByRoleIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/users/{user_id}/roles/{role_id}';
};

export type PostUsersByUserIdRolesByRoleIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostUsersByUserIdRolesByRoleIdError = PostUsersByUserIdRolesByRoleIdErrors[keyof PostUsersByUserIdRolesByRoleIdErrors];

export type PostUsersByUserIdRolesByRoleIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PostUsersByUserIdRolesByRoleIdResponse = PostUsersByUserIdRolesByRoleIdResponses[keyof PostUsersByUserIdRolesByRoleIdResponses];

export type DeleteUsersByUserIdScopesData = {
    /**
     * Scopes
     */
    body: Array<string>;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}/scopes';
};

export type DeleteUsersByUserIdScopesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUsersByUserIdScopesError = DeleteUsersByUserIdScopesErrors[keyof DeleteUsersByUserIdScopesErrors];

export type DeleteUsersByUserIdScopesResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type DeleteUsersByUserIdScopesResponse = DeleteUsersByUserIdScopesResponses[keyof DeleteUsersByUserIdScopesResponses];

export type PostUsersByUserIdScopesData = {
    /**
     * Scopes
     */
    body: Array<string>;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}/scopes';
};

export type PostUsersByUserIdScopesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostUsersByUserIdScopesError = PostUsersByUserIdScopesErrors[keyof PostUsersByUserIdScopesErrors];

export type PostUsersByUserIdScopesResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PostUsersByUserIdScopesResponse = PostUsersByUserIdScopesResponses[keyof PostUsersByUserIdScopesResponses];

export type PostRecipesUploadImageData = {
    body: BodyRecipesUploadRecipeImage;
    path?: never;
    query?: never;
    url: '/recipes/upload-image';
};

export type PostRecipesUploadImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRecipesUploadImageError = PostRecipesUploadImageErrors[keyof PostRecipesUploadImageErrors];

export type PostRecipesUploadImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRecipesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/recipes/';
};

export type GetRecipesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecipesError = GetRecipesErrors[keyof GetRecipesErrors];

export type GetRecipesResponses = {
    /**
     * Response Recipes-Read Recipes
     *
     * Successful Response
     */
    200: Array<RecipePublic>;
};

export type GetRecipesResponse = GetRecipesResponses[keyof GetRecipesResponses];

export type PostRecipesData = {
    body: RecipeCreate;
    path?: never;
    query?: never;
    url: '/recipes/';
};

export type PostRecipesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRecipesError = PostRecipesErrors[keyof PostRecipesErrors];

export type PostRecipesResponses = {
    /**
     * Successful Response
     */
    200: RecipePublic;
};

export type PostRecipesResponse = PostRecipesResponses[keyof PostRecipesResponses];

export type DeleteRecipesByRecipeIdData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/recipes/{recipe_id}';
};

export type DeleteRecipesByRecipeIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRecipesByRecipeIdError = DeleteRecipesByRecipeIdErrors[keyof DeleteRecipesByRecipeIdErrors];

export type DeleteRecipesByRecipeIdResponses = {
    /**
     * Successful Response
     */
    200: Recipe;
};

export type DeleteRecipesByRecipeIdResponse = DeleteRecipesByRecipeIdResponses[keyof DeleteRecipesByRecipeIdResponses];

export type GetRecipesByRecipeIdData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/recipes/{recipe_id}';
};

export type GetRecipesByRecipeIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecipesByRecipeIdError = GetRecipesByRecipeIdErrors[keyof GetRecipesByRecipeIdErrors];

export type GetRecipesByRecipeIdResponses = {
    /**
     * Successful Response
     */
    200: RecipePublic;
};

export type GetRecipesByRecipeIdResponse = GetRecipesByRecipeIdResponses[keyof GetRecipesByRecipeIdResponses];

export type PatchRecipesByRecipeIdData = {
    body: RecipeCreate;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/recipes/{recipe_id}';
};

export type PatchRecipesByRecipeIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchRecipesByRecipeIdError = PatchRecipesByRecipeIdErrors[keyof PatchRecipesByRecipeIdErrors];

export type PatchRecipesByRecipeIdResponses = {
    /**
     * Successful Response
     */
    200: RecipePublic;
};

export type PatchRecipesByRecipeIdResponse = PatchRecipesByRecipeIdResponses[keyof PatchRecipesByRecipeIdResponses];

export type GetIngredientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/ingredients/';
};

export type GetIngredientsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIngredientsError = GetIngredientsErrors[keyof GetIngredientsErrors];

export type GetIngredientsResponses = {
    /**
     * Response Ingredients-Get Ingredients
     *
     * Successful Response
     */
    200: Array<IngredientPublic>;
};

export type GetIngredientsResponse = GetIngredientsResponses[keyof GetIngredientsResponses];

export type PostIngredientsData = {
    body: IngredientCreate;
    path?: never;
    query?: never;
    url: '/ingredients/';
};

export type PostIngredientsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostIngredientsError = PostIngredientsErrors[keyof PostIngredientsErrors];

export type PostIngredientsResponses = {
    /**
     * Successful Response
     */
    200: IngredientPublic;
};

export type PostIngredientsResponse = PostIngredientsResponses[keyof PostIngredientsResponses];

export type DeleteIngredientsByIngredientIdData = {
    body?: never;
    path: {
        /**
         * Ingredient Id
         */
        ingredient_id: string;
    };
    query?: never;
    url: '/ingredients/{ingredient_id}';
};

export type DeleteIngredientsByIngredientIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteIngredientsByIngredientIdError = DeleteIngredientsByIngredientIdErrors[keyof DeleteIngredientsByIngredientIdErrors];

export type DeleteIngredientsByIngredientIdResponses = {
    /**
     * Successful Response
     */
    200: IngredientPublic;
};

export type DeleteIngredientsByIngredientIdResponse = DeleteIngredientsByIngredientIdResponses[keyof DeleteIngredientsByIngredientIdResponses];

export type GetIngredientsByIngredientIdData = {
    body?: never;
    path: {
        /**
         * Ingredient Id
         */
        ingredient_id: string;
    };
    query?: never;
    url: '/ingredients/{ingredient_id}';
};

export type GetIngredientsByIngredientIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIngredientsByIngredientIdError = GetIngredientsByIngredientIdErrors[keyof GetIngredientsByIngredientIdErrors];

export type GetIngredientsByIngredientIdResponses = {
    /**
     * Successful Response
     */
    200: IngredientPublic;
};

export type GetIngredientsByIngredientIdResponse = GetIngredientsByIngredientIdResponses[keyof GetIngredientsByIngredientIdResponses];

export type PatchIngredientsByIngredientIdData = {
    body: IngredientCreate;
    path: {
        /**
         * Ingredient Id
         */
        ingredient_id: string;
    };
    query?: never;
    url: '/ingredients/{ingredient_id}';
};

export type PatchIngredientsByIngredientIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchIngredientsByIngredientIdError = PatchIngredientsByIngredientIdErrors[keyof PatchIngredientsByIngredientIdErrors];

export type PatchIngredientsByIngredientIdResponses = {
    /**
     * Successful Response
     */
    200: IngredientPublic;
};

export type PatchIngredientsByIngredientIdResponse = PatchIngredientsByIngredientIdResponses[keyof PatchIngredientsByIngredientIdResponses];

export type GetGameData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/game/';
};

export type GetGameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGameError = GetGameErrors[keyof GetGameErrors];

export type GetGameResponses = {
    /**
     * Response Game-Read Game Sessions
     *
     * Successful Response
     */
    200: Array<GameSessionPublic>;
};

export type GetGameResponse = GetGameResponses[keyof GetGameResponses];

export type PostGameData = {
    body: GameSessionCreate;
    path?: never;
    query?: never;
    url: '/game/';
};

export type PostGameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostGameError = PostGameErrors[keyof PostGameErrors];

export type PostGameResponses = {
    /**
     * Successful Response
     */
    200: GameSessionPublic;
};

export type PostGameResponse = PostGameResponses[keyof PostGameResponses];

export type GetGameDrinksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/game/drinks';
};

export type GetGameDrinksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGameDrinksError = GetGameDrinksErrors[keyof GetGameDrinksErrors];

export type GetGameDrinksResponses = {
    /**
     * Response Game-Read Drinks
     *
     * Successful Response
     */
    200: Array<DrinkPublic>;
};

export type GetGameDrinksResponse = GetGameDrinksResponses[keyof GetGameDrinksResponses];

export type PostGameDrinksData = {
    body: DrinkCreate;
    path?: never;
    query?: never;
    url: '/game/drinks';
};

export type PostGameDrinksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostGameDrinksError = PostGameDrinksErrors[keyof PostGameDrinksErrors];

export type PostGameDrinksResponses = {
    /**
     * Successful Response
     */
    200: DrinkPublic;
};

export type PostGameDrinksResponse = PostGameDrinksResponses[keyof PostGameDrinksResponses];

export type DeleteGameDrinksByDrinkIdData = {
    body?: never;
    path: {
        /**
         * Drink Id
         */
        drink_id: string;
    };
    query?: never;
    url: '/game/drinks/{drink_id}';
};

export type DeleteGameDrinksByDrinkIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGameDrinksByDrinkIdError = DeleteGameDrinksByDrinkIdErrors[keyof DeleteGameDrinksByDrinkIdErrors];

export type DeleteGameDrinksByDrinkIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PatchGameDrinksByDrinkIdData = {
    body: DrinkCreate;
    path: {
        /**
         * Drink Id
         */
        drink_id: string;
    };
    query?: never;
    url: '/game/drinks/{drink_id}';
};

export type PatchGameDrinksByDrinkIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchGameDrinksByDrinkIdError = PatchGameDrinksByDrinkIdErrors[keyof PatchGameDrinksByDrinkIdErrors];

export type PatchGameDrinksByDrinkIdResponses = {
    /**
     * Successful Response
     */
    200: DrinkPublic;
};

export type PatchGameDrinksByDrinkIdResponse = PatchGameDrinksByDrinkIdResponses[keyof PatchGameDrinksByDrinkIdResponses];

export type DeleteGameByGameSessionIdData = {
    body?: never;
    path: {
        /**
         * Game Session Id
         */
        game_session_id: string;
    };
    query?: never;
    url: '/game/{game_session_id}';
};

export type DeleteGameByGameSessionIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGameByGameSessionIdError = DeleteGameByGameSessionIdErrors[keyof DeleteGameByGameSessionIdErrors];

export type DeleteGameByGameSessionIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetGameByGameSessionIdData = {
    body?: never;
    path: {
        /**
         * Game Session Id
         */
        game_session_id: string;
    };
    query?: never;
    url: '/game/{game_session_id}';
};

export type GetGameByGameSessionIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGameByGameSessionIdError = GetGameByGameSessionIdErrors[keyof GetGameByGameSessionIdErrors];

export type GetGameByGameSessionIdResponses = {
    /**
     * Successful Response
     */
    200: GameSessionPublic;
};

export type GetGameByGameSessionIdResponse = GetGameByGameSessionIdResponses[keyof GetGameByGameSessionIdResponses];

export type PostGameByGameSessionIdPlayerData = {
    body: GamePlayerCreate;
    path: {
        /**
         * Game Session Id
         */
        game_session_id: string;
    };
    query?: never;
    url: '/game/{game_session_id}/player';
};

export type PostGameByGameSessionIdPlayerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostGameByGameSessionIdPlayerError = PostGameByGameSessionIdPlayerErrors[keyof PostGameByGameSessionIdPlayerErrors];

export type PostGameByGameSessionIdPlayerResponses = {
    /**
     * Successful Response
     */
    200: GamePlayerPublic;
};

export type PostGameByGameSessionIdPlayerResponse = PostGameByGameSessionIdPlayerResponses[keyof PostGameByGameSessionIdPlayerResponses];

export type PostGameByGameSessionIdTeamData = {
    body: GameTeamCreate;
    path: {
        /**
         * Game Session Id
         */
        game_session_id: string;
    };
    query?: never;
    url: '/game/{game_session_id}/team';
};

export type PostGameByGameSessionIdTeamErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostGameByGameSessionIdTeamError = PostGameByGameSessionIdTeamErrors[keyof PostGameByGameSessionIdTeamErrors];

export type PostGameByGameSessionIdTeamResponses = {
    /**
     * Successful Response
     */
    200: GameTeamPublic;
};

export type PostGameByGameSessionIdTeamResponse = PostGameByGameSessionIdTeamResponses[keyof PostGameByGameSessionIdTeamResponses];

export type DeleteGameByGameSessionIdPlayerByGamePlayerIdData = {
    body?: never;
    path: {
        /**
         * Game Session Id
         */
        game_session_id: string;
        /**
         * Game Player Id
         */
        game_player_id: string;
    };
    query?: never;
    url: '/game/{game_session_id}/player/{game_player_id}';
};

export type DeleteGameByGameSessionIdPlayerByGamePlayerIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGameByGameSessionIdPlayerByGamePlayerIdError = DeleteGameByGameSessionIdPlayerByGamePlayerIdErrors[keyof DeleteGameByGameSessionIdPlayerByGamePlayerIdErrors];

export type DeleteGameByGameSessionIdPlayerByGamePlayerIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PatchGameByGameSessionIdPlayerByGamePlayerIdData = {
    body: GamePlayerUpdate;
    path: {
        /**
         * Game Session Id
         */
        game_session_id: string;
        /**
         * Game Player Id
         */
        game_player_id: string;
    };
    query?: never;
    url: '/game/{game_session_id}/player/{game_player_id}';
};

export type PatchGameByGameSessionIdPlayerByGamePlayerIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchGameByGameSessionIdPlayerByGamePlayerIdError = PatchGameByGameSessionIdPlayerByGamePlayerIdErrors[keyof PatchGameByGameSessionIdPlayerByGamePlayerIdErrors];

export type PatchGameByGameSessionIdPlayerByGamePlayerIdResponses = {
    /**
     * Successful Response
     */
    200: GamePlayerPublic;
};

export type PatchGameByGameSessionIdPlayerByGamePlayerIdResponse = PatchGameByGameSessionIdPlayerByGamePlayerIdResponses[keyof PatchGameByGameSessionIdPlayerByGamePlayerIdResponses];

export type DeleteGameByGameSessionIdTeamByGameTeamIdData = {
    body?: never;
    path: {
        /**
         * Game Session Id
         */
        game_session_id: string;
        /**
         * Game Team Id
         */
        game_team_id: string;
    };
    query?: never;
    url: '/game/{game_session_id}/team/{game_team_id}';
};

export type DeleteGameByGameSessionIdTeamByGameTeamIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGameByGameSessionIdTeamByGameTeamIdError = DeleteGameByGameSessionIdTeamByGameTeamIdErrors[keyof DeleteGameByGameSessionIdTeamByGameTeamIdErrors];

export type DeleteGameByGameSessionIdTeamByGameTeamIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PatchGameByGameSessionIdPlayerByGamePlayerIdDrinkData = {
    body: GamePlayerDrinkLinkCreate;
    path: {
        /**
         * Game Session Id
         */
        game_session_id: string;
        /**
         * Game Player Id
         */
        game_player_id: string;
    };
    query?: never;
    url: '/game/{game_session_id}/player/{game_player_id}/drink';
};

export type PatchGameByGameSessionIdPlayerByGamePlayerIdDrinkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchGameByGameSessionIdPlayerByGamePlayerIdDrinkError = PatchGameByGameSessionIdPlayerByGamePlayerIdDrinkErrors[keyof PatchGameByGameSessionIdPlayerByGamePlayerIdDrinkErrors];

export type PatchGameByGameSessionIdPlayerByGamePlayerIdDrinkResponses = {
    /**
     * Successful Response
     */
    200: GamePlayerPublic;
};

export type PatchGameByGameSessionIdPlayerByGamePlayerIdDrinkResponse = PatchGameByGameSessionIdPlayerByGamePlayerIdDrinkResponses[keyof PatchGameByGameSessionIdPlayerByGamePlayerIdDrinkResponses];

export type GetGameByGameSessionIdUpdatesData = {
    body?: never;
    path: {
        /**
         * Game Session Id
         */
        game_session_id: string;
    };
    query?: never;
    url: '/game/{game_session_id}/updates';
};

export type GetGameByGameSessionIdUpdatesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGameByGameSessionIdUpdatesError = GetGameByGameSessionIdUpdatesErrors[keyof GetGameByGameSessionIdUpdatesErrors];

export type GetGameByGameSessionIdUpdatesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/login/access-token';
};

export type PostLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostLoginAccessTokenError = PostLoginAccessTokenErrors[keyof PostLoginAccessTokenErrors];

export type PostLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type PostLoginAccessTokenResponse = PostLoginAccessTokenResponses[keyof PostLoginAccessTokenResponses];

export type PostLoginRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/login/refresh';
};

export type PostLoginRefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostLoginRefreshError = PostLoginRefreshErrors[keyof PostLoginRefreshErrors];

export type PostLoginRefreshResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type PostLoginRefreshResponse = PostLoginRefreshResponses[keyof PostLoginRefreshResponses];

export type PostLogoutData = {
    /**
     * Body
     */
    body?: RefreshRequest | null;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostLogoutError = PostLogoutErrors[keyof PostLogoutErrors];

export type PostLogoutResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PostLogoutResponse = PostLogoutResponses[keyof PostLogoutResponses];

export type PostLoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login/test-token';
};

export type PostLoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PostLoginTestTokenResponse = PostLoginTestTokenResponses[keyof PostLoginTestTokenResponses];

export type PostPasswordRecoveryByEmailData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/password-recovery/{email}';
};

export type PostPasswordRecoveryByEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPasswordRecoveryByEmailError = PostPasswordRecoveryByEmailErrors[keyof PostPasswordRecoveryByEmailErrors];

export type PostPasswordRecoveryByEmailResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PostPasswordRecoveryByEmailResponse = PostPasswordRecoveryByEmailResponses[keyof PostPasswordRecoveryByEmailResponses];

export type PostResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/reset-password/';
};

export type PostResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostResetPasswordError = PostResetPasswordErrors[keyof PostResetPasswordErrors];

export type PostResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PostResetPasswordResponse = PostResetPasswordResponses[keyof PostResetPasswordResponses];

export type PostPasswordRecoveryHtmlContentByEmailData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/password-recovery-html-content/{email}';
};

export type PostPasswordRecoveryHtmlContentByEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPasswordRecoveryHtmlContentByEmailError = PostPasswordRecoveryHtmlContentByEmailErrors[keyof PostPasswordRecoveryHtmlContentByEmailErrors];

export type PostPasswordRecoveryHtmlContentByEmailResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type PostPasswordRecoveryHtmlContentByEmailResponse = PostPasswordRecoveryHtmlContentByEmailResponses[keyof PostPasswordRecoveryHtmlContentByEmailResponses];

export type GetRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/roles/';
};

export type GetRolesResponses = {
    /**
     * Response Roles-Read Roles
     *
     * Successful Response
     */
    200: Array<RolePublic>;
};

export type GetRolesResponse = GetRolesResponses[keyof GetRolesResponses];

export type PostRolesData = {
    body: RoleCreate;
    path?: never;
    query?: never;
    url: '/roles/';
};

export type PostRolesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRolesError = PostRolesErrors[keyof PostRolesErrors];

export type PostRolesResponses = {
    /**
     * Successful Response
     */
    200: RolePublic;
};

export type PostRolesResponse = PostRolesResponses[keyof PostRolesResponses];

export type DeleteRolesByRoleIdData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/roles/{role_id}';
};

export type DeleteRolesByRoleIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRolesByRoleIdError = DeleteRolesByRoleIdErrors[keyof DeleteRolesByRoleIdErrors];

export type DeleteRolesByRoleIdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteRolesByRoleIdResponse = DeleteRolesByRoleIdResponses[keyof DeleteRolesByRoleIdResponses];

export type GetRolesByRoleIdData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/roles/{role_id}';
};

export type GetRolesByRoleIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRolesByRoleIdError = GetRolesByRoleIdErrors[keyof GetRolesByRoleIdErrors];

export type GetRolesByRoleIdResponses = {
    /**
     * Successful Response
     */
    200: RolePublic;
};

export type GetRolesByRoleIdResponse = GetRolesByRoleIdResponses[keyof GetRolesByRoleIdResponses];

export type PutRolesByRoleIdData = {
    body: RoleUpdate;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/roles/{role_id}';
};

export type PutRolesByRoleIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutRolesByRoleIdError = PutRolesByRoleIdErrors[keyof PutRolesByRoleIdErrors];

export type PutRolesByRoleIdResponses = {
    /**
     * Successful Response
     */
    200: RolePublic;
};

export type PutRolesByRoleIdResponse = PutRolesByRoleIdResponses[keyof PutRolesByRoleIdResponses];

export type GetRolesTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/roles/templates/';
};

export type GetRolesTemplatesResponses = {
    /**
     * Response Roles-List Role Templates
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetRolesTemplatesResponse = GetRolesTemplatesResponses[keyof GetRolesTemplatesResponses];

export type PostRolesFromTemplateByTemplateKeyData = {
    body?: never;
    path: {
        /**
         * Template Key
         */
        template_key: string;
    };
    query?: never;
    url: '/roles/from-template/{template_key}';
};

export type PostRolesFromTemplateByTemplateKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRolesFromTemplateByTemplateKeyError = PostRolesFromTemplateByTemplateKeyErrors[keyof PostRolesFromTemplateByTemplateKeyErrors];

export type PostRolesFromTemplateByTemplateKeyResponses = {
    /**
     * Successful Response
     */
    200: RolePublic;
};

export type PostRolesFromTemplateByTemplateKeyResponse = PostRolesFromTemplateByTemplateKeyResponses[keyof PostRolesFromTemplateByTemplateKeyResponses];

export type GetRolesScopesAvailableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/roles/scopes/available';
};

export type GetRolesScopesAvailableResponses = {
    /**
     * Response Roles-Get Available Scopes
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetRolesScopesAvailableResponse = GetRolesScopesAvailableResponses[keyof GetRolesScopesAvailableResponses];
